/*
 * Principal.java
 *
 * Esse projeto é só um esqueleto para ilustrar os conceitos de Herança e 
 * Polimorfismo.
 * 
 * Será necessário criar mais classes para representar:
 * - Cavaleiro e Arqueiro
 * 
 * Será necessário pensar em uma forma para organizar todos os personagens em
 * uma única ArrayList
 * 
 * Será necessário pensar em uma forma para permitir 'mover' ou 'atacar'
 * todos os personagens, somente aldeões, somente arqueiros ou somente cavaleiros.
 * 
 * Pensar em uma solução com Classe Abstrata ou Interfaces
 * 
 * Created on 06/10/2011, 16:22:51
 */
package poo;

import java.util.Random;

/**
 *
 * @author Emerson Ribeiro de Mello - mello@ifsc.edu.br
 * http://www.sj.ifsc.edu.br/~mello
 */
public class Principal extends javax.swing.JFrame {

   private Random sorteio;

   /** Creates new form Principal */
   public Principal() {
      initComponents();
      this.setLocationRelativeTo(null);
      this.sorteio = new Random();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPTela = new Tela(this);
        jPLateral = new javax.swing.JPanel();
        jPMovimentar = new javax.swing.JPanel();
        jRBAldeao = new javax.swing.JRadioButton();
        jRBArqueiro = new javax.swing.JRadioButton();
        jRBCavaleiro = new javax.swing.JRadioButton();
        jRBTodos = new javax.swing.JRadioButton();
        jBCima = new javax.swing.JButton();
        jBBaixo = new javax.swing.JButton();
        jBDireita = new javax.swing.JButton();
        jBAtacar = new javax.swing.JButton();
        JrbGuerreiro = new javax.swing.JRadioButton();
        jBEsquerda = new javax.swing.JButton();
        jPCriar = new javax.swing.JPanel();
        jBAldeao = new javax.swing.JButton();
        jBCavaleiro = new javax.swing.JButton();
        jBArqueiro = new javax.swing.JButton();
        Jbguerreiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("J2D - Conceitos de Herança e Polimorfismo");
        setResizable(false);

        javax.swing.GroupLayout jPTelaLayout = new javax.swing.GroupLayout(jPTela);
        jPTela.setLayout(jPTelaLayout);
        jPTelaLayout.setHorizontalGroup(
            jPTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        jPTelaLayout.setVerticalGroup(
            jPTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jPMovimentar.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimentar"));

        buttonGroup1.add(jRBAldeao);
        jRBAldeao.setSelected(true);
        jRBAldeao.setText("Aldeão");

        buttonGroup1.add(jRBArqueiro);
        jRBArqueiro.setText("Arqueiro");
        jRBArqueiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBArqueiroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBCavaleiro);
        jRBCavaleiro.setText("Cavaleiro");

        buttonGroup1.add(jRBTodos);
        jRBTodos.setText("Todos");
        jRBTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTodosActionPerformed(evt);
            }
        });

        jBCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N
        jBCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCimaActionPerformed(evt);
            }
        });

        jBBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N
        jBBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBaixoActionPerformed(evt);
            }
        });

        jBDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/direita.png"))); // NOI18N
        jBDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDireitaActionPerformed(evt);
            }
        });

        jBAtacar.setText("Atacar");
        jBAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtacarActionPerformed(evt);
            }
        });

        buttonGroup1.add(JrbGuerreiro);
        JrbGuerreiro.setText("Guerreiro");
        JrbGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbGuerreiroActionPerformed(evt);
            }
        });

        jBEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esquerda.png"))); // NOI18N
        jBEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEsquerdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMovimentarLayout = new javax.swing.GroupLayout(jPMovimentar);
        jPMovimentar.setLayout(jPMovimentarLayout);
        jPMovimentarLayout.setHorizontalGroup(
            jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMovimentarLayout.createSequentialGroup()
                .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMovimentarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBAtacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPMovimentarLayout.createSequentialGroup()
                        .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPMovimentarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPMovimentarLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPMovimentarLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jRBCavaleiro)
                                        .addGap(14, 14, 14)
                                        .addComponent(jRBTodos))
                                    .addGroup(jPMovimentarLayout.createSequentialGroup()
                                        .addComponent(jRBAldeao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JrbGuerreiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBArqueiro))
                                    .addGroup(jPMovimentarLayout.createSequentialGroup()
                                        .addComponent(jBEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPMovimentarLayout.setVerticalGroup(
            jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMovimentarLayout.createSequentialGroup()
                .addComponent(jBAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBAldeao)
                    .addComponent(JrbGuerreiro)
                    .addComponent(jRBArqueiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBTodos)
                    .addComponent(jRBCavaleiro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCima, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMovimentarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPMovimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBDireita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jBBaixo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        jPCriar.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar"));

        jBAldeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aldeao.png"))); // NOI18N
        jBAldeao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAldeaoActionPerformed(evt);
            }
        });

        jBCavaleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cavaleiro.png"))); // NOI18N
        jBCavaleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCavaleiroActionPerformed(evt);
            }
        });

        jBArqueiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arqueiro.png"))); // NOI18N
        jBArqueiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBArqueiroActionPerformed(evt);
            }
        });

        Jbguerreiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guerreiro.png"))); // NOI18N
        Jbguerreiro.setText("Guerreiro");
        Jbguerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbguerreiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCriarLayout = new javax.swing.GroupLayout(jPCriar);
        jPCriar.setLayout(jPCriarLayout);
        jPCriarLayout.setHorizontalGroup(
            jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCriarLayout.createSequentialGroup()
                .addGroup(jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBAldeao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jbguerreiro, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCavaleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBArqueiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPCriarLayout.setVerticalGroup(
            jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCriarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCavaleiro, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jBAldeao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jbguerreiro, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jBArqueiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPLateralLayout = new javax.swing.GroupLayout(jPLateral);
        jPLateral.setLayout(jPLateralLayout);
        jPLateralLayout.setHorizontalGroup(
            jPLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLateralLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPMovimentar, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPLateralLayout.setVerticalGroup(
            jPLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPCriar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPMovimentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPCriar.getAccessibleContext().setAccessibleName("Criar Personagens");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void jBAldeaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAldeaoActionPerformed

      //obtendo o tamanho do JPanel TELA
      int largura = this.jPTela.getWidth();
      int altura = this.jPTela.getHeight();

      // criando o aldeao em um local aleatorio
      int x = this.sorteio.nextInt(largura - 50);
      int y = this.sorteio.nextInt(altura - 50);
      if (x < 0) { // garantindo que x não esteja fora do limite do JPanel
         x = 0;
      }
      if (y < 0) { // garantindo que x não esteja fora do limite do JPanel
         y = 0;
      }

      // invocando o método criarAldeao da classe Tela.
      // Foi necessário a coerção de tipos pois jPTela é do tipo JPanel.
      // Isso só foi possível pois Tela é uma subclasse de JPanel.
      ((Tela) this.jPTela).criaPersonagem(x, y, "aldeao");

   }//GEN-LAST:event_jBAldeaoActionPerformed

   private void jBCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCimaActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(0,"aldeao");
      }
      if (jRBArqueiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(0,"arqueiro");
      }
      if (jRBCavaleiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(0,"cavaleiro");
      }
      if(JrbGuerreiro.isSelected()){
          ((Tela) this.jPTela).movimentarPersonagem(0,"guerreiro");
      }
      if (jRBTodos.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(0,"todos");
      }
      
      
   }//GEN-LAST:event_jBCimaActionPerformed

   private void jBBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBaixoActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(1,"aldeao");
      }
      if (jRBArqueiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(1,"arqueiro");
      }
      if (jRBCavaleiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(1,"cavaleiro");
      }
      if(JrbGuerreiro.isSelected()){
          ((Tela) this.jPTela).movimentarPersonagem(1,"guerreiro");
      }
      if (jRBTodos.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(1,"todos");
      }
   }//GEN-LAST:event_jBBaixoActionPerformed

   private void jBEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEsquerdaActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(2,"aldeao");
      }
      if (jRBArqueiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(2,"arqueiro");
      }
      if (jRBCavaleiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(2,"cavaleiro");
      }
      if(JrbGuerreiro.isSelected()){
          ((Tela) this.jPTela).movimentarPersonagem(2,"guerreiro");
      }
      if (jRBTodos.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(2,"todos");
      }
   }//GEN-LAST:event_jBEsquerdaActionPerformed

   private void jBDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDireitaActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(3,"aldeao");
      }
      if (jRBArqueiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(3,"arqueiro");
      }
      if (jRBCavaleiro.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(3,"cavaleiro");
      }
      if(JrbGuerreiro.isSelected()){
          ((Tela) this.jPTela).movimentarPersonagem(3,"guerreiro");
      }
      if (jRBTodos.isSelected()) {
         ((Tela) this.jPTela).movimentarPersonagem(3,"todos");
      }
   }//GEN-LAST:event_jBDireitaActionPerformed

   private void jBAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtacarActionPerformed
      if (jRBAldeao.isSelected()) {
         ((Tela) this.jPTela).atacarPersonagem("aldeao");
      }
      if (jRBArqueiro.isSelected()) {
         ((Tela) this.jPTela).atacarPersonagem("arqueiro");
      }
      if (jRBCavaleiro.isSelected()) {
         ((Tela) this.jPTela).atacarPersonagem("cavaleiro");
      }
      if(JrbGuerreiro.isSelected()){
          ((Tela) this.jPTela).atacarPersonagem("guerreiro");
      }
      if(jRBTodos.isSelected()){
          ((Tela) this.jPTela).atacarPersonagem("guerreiro");
          ((Tela) this.jPTela).atacarPersonagem("cavaleiro");
          ((Tela) this.jPTela).atacarPersonagem("arqueiro");
          ((Tela) this.jPTela).atacarPersonagem("aldeao");
      }
   }//GEN-LAST:event_jBAtacarActionPerformed

    private void jBArqueiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBArqueiroActionPerformed
        // TODO add your handling code here:
       
      //obtendo o tamanho do JPanel TELA
      int largura = this.jPTela.getWidth();
      int altura = this.jPTela.getHeight();

      // criando o aldeao em um local aleatorio
      int x = this.sorteio.nextInt(largura - 50);
      int y = this.sorteio.nextInt(altura - 50);
      if (x < 0) { // garantindo que x não esteja fora do limite do JPanel
         x = 0;
      }
      if (y < 0) { // garantindo que x não esteja fora do limite do JPanel
         y = 0;
      }

      // invocando o método criarAldeao da classe Tela.
      // Foi necessário a coerção de tipos pois jPTela é do tipo JPanel.
      // Isso só foi possível pois Tela é uma subclasse de JPanel.
      ((Tela) this.jPTela).criaPersonagem(x, y, "arqueiro");
    }//GEN-LAST:event_jBArqueiroActionPerformed

    private void jRBArqueiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBArqueiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBArqueiroActionPerformed

    private void jRBTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBTodosActionPerformed

    private void jBCavaleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCavaleiroActionPerformed
        // TODO add your handling code here:
        //obtendo o tamanho do JPanel TELA
      int largura = this.jPTela.getWidth();
      int altura = this.jPTela.getHeight();

      // criando o aldeao em um local aleatorio
      int x = this.sorteio.nextInt(largura - 50);
      int y = this.sorteio.nextInt(altura - 50);
      if (x < 0) { // garantindo que x não esteja fora do limite do JPanel
         x = 0;
      }
      if (y < 0) { // garantindo que x não esteja fora do limite do JPanel
         y = 0;
      }

      // invocando o método criarAldeao da classe Tela.
      // Foi necessário a coerção de tipos pois jPTela é do tipo JPanel.
      // Isso só foi possível pois Tela é uma subclasse de JPanel.
      ((Tela) this.jPTela).criaPersonagem(x, y, "cavaleiro");
    }//GEN-LAST:event_jBCavaleiroActionPerformed

    private void JbguerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbguerreiroActionPerformed
      int largura = this.jPTela.getWidth();
      int altura = this.jPTela.getHeight();

      // criando o aldeao em um local aleatorio
      int x = this.sorteio.nextInt(largura - 50);
      int y = this.sorteio.nextInt(altura - 50);
      if (x < 0) { // garantindo que x não esteja fora do limite do JPanel
         x = 0;
      }
      if (y < 0) { // garantindo que x não esteja fora do limite do JPanel
         y = 0;
      }

      // invocando o método criarAldeao da classe Tela.
      // Foi necessário a coerção de tipos pois jPTela é do tipo JPanel.
      // Isso só foi possível pois Tela é uma subclasse de JPanel.
      ((Tela) this.jPTela).criaPersonagem(x, y, "guerreiro");
        // TODO add your handling code here:
    }//GEN-LAST:event_JbguerreiroActionPerformed

    private void JrbGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbGuerreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JrbGuerreiroActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new Principal().setVisible(true);
         }
      });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbguerreiro;
    private javax.swing.JRadioButton JrbGuerreiro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAldeao;
    private javax.swing.JButton jBArqueiro;
    private javax.swing.JButton jBAtacar;
    private javax.swing.JButton jBBaixo;
    private javax.swing.JButton jBCavaleiro;
    private javax.swing.JButton jBCima;
    private javax.swing.JButton jBDireita;
    private javax.swing.JButton jBEsquerda;
    private javax.swing.JPanel jPCriar;
    private javax.swing.JPanel jPLateral;
    private javax.swing.JPanel jPMovimentar;
    private javax.swing.JPanel jPTela;
    private javax.swing.JRadioButton jRBAldeao;
    private javax.swing.JRadioButton jRBArqueiro;
    private javax.swing.JRadioButton jRBCavaleiro;
    private javax.swing.JRadioButton jRBTodos;
    // End of variables declaration//GEN-END:variables
}
